const appname = "fMart";
const appversion = "Version 1.0.0";
const credits = "@Fahim Shahariar";
const email = "Email";
const emailHint = "fahim@gmail.com";
const password = "Password";
const passHint = "******";
const forgotpass = "Forgot Password";
const reTypePass = "Retype Password";
const name = "Name";
const nameHint = "Fahim Shahariar";
const login = "Log In";
const signup = "Sign Up";
const createNewAccount = "or, Create a new account";
const loginWith = "Log in with";
const privacy = "Privacy Policy";
const terms = "Terms and Condtion";
const already = "Already have an account? ";

const home = "Home", category = "categories", cart = "Cart", account = "Account";